spring:
  application:
    name: user-api-service

  r2dbc:
    url: r2dbc:mysql://localhost:3306/ecommerce?sslMode=DISABLED&allowPublicKeyRetrieval=true&useServerPrepareStatement=true
    username: root
    password: pass

  sql:
    init:
      mode: always
      platform: mysql

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    dev.miku.r2dbc.mysql: DEBUG

server:
  port: 8010






