spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-API-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: lb://ORDER-API-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: lb://USER-API-SERVICE
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

server:
  port: 9090
  address: 0.0.0.0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/