spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-API-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
            
        - id: order-service
          uri: lb://ORDER-API-SERVICE
          predicates:
            - Path=/order/**
          filters:
              - StripPrefix=1

server:
  port: 9090

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
