spring:
  application:
    name: product-api-service

  r2dbc:
    url: r2dbc:mysql://localhost:3306/ecommerce?sslMode=DISABLED&allowPublicKeyRetrieval=true&useServerPrepareStatement=true
    username: root
    password: pass

  sql:
    init:
      mode: always
      platform: mysql

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 6000
    password: ""   # keep empty if no password

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    dev.miku.r2dbc.mysql: DEBUG

server:
  port: 8090

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/




